services:

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    container_name: jenkins-server
    env_file:
      - .env
    ports:
      - $JENKINS_PORT:$JENKINS_PORT
      - $JENKINS_PORT_MASTER_SLAVE:$JENKINS_PORT_MASTER_SLAVE
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - C:\Program Files\Docker\Docker:/usr/bin/docker


  agent:
    image: jenkins/ssh-agent:jdk11
    privileged: true
    user: root
    container_name: agent
    expose:
      - 22
    env_file:
      - .env
    environment:
      - $JENKINS_AGENT_SSH_PUBKEY=$JENKINS_AGENT_SSH_PUBKEY


volumes:
  jenkins-data:
    external: true

networks:
  default:
      name: jenkins-net
      external: true