server:
  port: ${AUTH_PORT_SOURCE:8061}
  # error.include-message: always

#===============================================================================

## Application Common properties
application:

  self.active.version: 1.0

  b2b:
    feign:

      mdm:
        enabled: true
        service-id: mdm-dev-service
        context-path: mdm
        #service-lb : lb://mdm-dev-service
        service-name: ${application.b2b.feign.mdm.service-id}/${application.b2b.feign.mdm.context-path}
        #service-name: ${application.b2b.feign.mdm.service-lb}

#===============================================================================
#=================> Logging config

# Logging en mode debug pour le package feign
logging:
  level:
    org.solar.system.auth.api.feign: DEBUG

#===============================================================================

# rsa config : use RSA 512

rsa:
  key:
    publicKeyFile: ${PUB_KEY_PATH:C:\mfichtali\projects\solar-depot\ms-auth-parent\launch\${spring.profiles.active}-keys\rsa_pub_key}
    privateKeyFile: ${PRIV_KEY_PATH:C:\mfichtali\projects\solar-depot\ms-auth-parent\launch\${spring.profiles.active}-keys\rsa_priv_key.ppk}
    secret: ${RSA_SECRET:5381FDF3A97C8FD49AECE6B7B3D9}
    
#===============================================================================

spring:
  # application:
  #   name : ${application.name-key}-dev-service
  output.ansi.enabled: ALWAYS
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${AUTH_PG_DB_SERVICE:localhost:5442}/${AUTH_PG_DB_NAME:solar-auth-dev}
    username: ${AUTH_PG_DB_USER:d_auth_user}
    password: ${AUTH_PG_DB_PASSWORD:d_auth_user} # local password : javax123
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 20
      poolName: HIKARI-AUTH-DEV
      minimumIdle: 2
      leak-detection-threshold: 60000
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      jdbc.lob.non_contextual_creation: true
    properties:
      org.hibernate.envers.audit_table_suffix: _AUTH_DEV_LOG
      hibernate.format_sql: true # only in dev
      hibernate.id.new_generator_mappings: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.hbm2ddl.auto: none
  flyway:
    enabled: true # change value for taking new files sql
    # locations: ${FLYWAY_LOCATIONS:filesystem:C:/mfichtali/projects/solar-depot/ms-auth-parent/script/dev-pg} # separated by comma
    locations: ${FLYWAY_LOCATIONS:filesystem:D:/mfichtali/depots/ms-auth-parent/script/dev-pg} # separated by comma
    lockRetryCount: 10