server:
  port: ${AUTH_PORT_SOURCE:8061}
  error.include-message: always
    
#===============================================================================

# rsa config : use RSA 512

rsa:
  key:
    publicKeyFile: ${PUB_KEY_PATH:C:\mfichtali\solar-gitlab\ms-auth-parent\launch\${spring.profiles.active}-keys\id_solar_rsa.pub}
    privateKeyFile: ${PRIV_KEY_PATH:C:\mfichtali\solar-gitlab\ms-auth-parent\launch\${spring.profiles.active}-keys\id_solar_rsa}
    secret: ${RSA_SECRET:2BCB3D636435A4C8478F21A7AEE8B}
    
#===============================================================================

spring:
  application:
    name : ${application.name-key}-rec-service
  output.ansi.enabled: ALWAYS
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${AUTH_PG_DB_SERVICE:localhost:5443}/${AUTH_PG_DB_NAME:solar-auth-recette}
    username: ${AUTH_PG_DB_USER:r_auth_user}
    password: ${AUTH_PG_DB_PASSWORD:r_auth_user} # local password : javax123
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 20
      poolName: HIKARI-AUTH-REC
      minimumIdle: 2
      leak-detection-threshold: 60000
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: false # only in dev
      hibernate.id.new_generator_mappings: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.hbm2ddl.auto: none
  flyway:
    enabled: true # change value for taking new files sql
    locations: ${FLYWAY_LOCATIONS:filesystem:C:/mfichtali/solar-gitlab/ms-auth-parent/script/rec-pg} # separated by comma