#===============================================================================

server:
  port: ${RENTAL_SOURCE_PORT:8091}
  error.include-message: always

#===============================================================================

## Application Common properties
application:

  self.active.version: 1.0

  b2b:
    feign:

      mdm:
        enabled: true
        service-id: mdm-dev-service
        context-path: mdm
        service-name: ${application.b2b.feign.mdm.service-id}/${application.b2b.feign.mdm.context-path}

#===============================================================================
#================ > Spring config

spring:
  # application:
  #   name : ${application.name-key}-dev-service
  # output.ansi.enabled: ALWAYS
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${RENTAL_PG_DB_SERVICE:localhost:5472}/${RENTAL_PG_DB_NAME:solar-rental-dev}
    username: ${RENTAL_PG_DB_USER:d_rental_user}
    password: ${RENTAL_PG_DB_PASSWORD:d_rental_user} # local password : javax123
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 20
      poolName: HIKARI-RENTAL-DEV
      minimumIdle: 2
      leak-detection-threshold: 60000
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      jdbc.lob.non_contextual_creation: true
    properties:
      org.hibernate.envers.audit_table_suffix: _RENTAL_DEV_LOG
      hibernate.format_sql: true # only in dev
      hibernate.id.new_generator_mappings: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.hbm2ddl.auto: none
  flyway:
    enabled: true # change value for taking new files sql
    locations: ${FLYWAY_LOCATIONS:filesystem:D:/mfichtali/depots/ms-rental-parent/script/dev-pg} # separated by comma
    #locations: ${FLYWAY_LOCATIONS:filesystem:/home/mfichtali/workspace/depôt/ms-rental-parent/script/dev-pg} # separated by comma
    lockRetryCount: 10