#===============================================================================

server:
  servlet:
    context-path: /${application.name-key}

#===============================================================================

## Application Common properties
application:

  # Enable Kafka Produce message
  kafka.producer.enabled: true

  # Swagger Config
  swagger:
    title: Rental API
    description: Rental API Information
    termsOfService: http://swagger.io/terms/
    licenseName: Apache 2.0
    licenseUrl: http://springdoc.org
    activeVersion: 1.0 # swagger version manually changed

    actuator:
      group-label: rental-actuator
      paths-to-match: /actuator/**
      #paths-to-exclude: /api/v1.0/**,/api/v1.1/**

    rental-insurance:
      group-label: rental-insurance
      paths-to-match: /api/insurance-vehicle/**
      paths-to-exclude: /api/insurance-vehicle/v1.0/**


#===============================================================================

# The OpenAPI definitions are in JSON format by default. For yaml format, we can obtain the
# definitions at : http://localhost:8080/api-docs.yaml
# default url : http://localhost:8080/v3/api-docs/
# swagger UI url : http://localhost:8080/swagger-ui.html
springdoc:
  #use-management-port: true
  show-actuator: true
  #  paths-to-match: /actuator/**, /api/**
  #  paths-to-exclude: /api/v1.0/**, /api/v2.0/**    # /api/version/** : api version admin
  #  packages-to-scan: org.solar.system.auth.api.rest # package1, package2
  api-docs:
    enabled: true # Disabling the /api-docs enpoint
  swagger-ui:
    enabled: true # Disabling the /swagger-api enpoint
    defaultModelsExpandDepth: -1
    operationsSorter: method

#========================= > Spring config

spring:
  jpa.open-in-view: false
  kafka:
    enabled: true
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

#===============================================================================
#========================= > Feign config

feign:

  retry:
    maxAttempt: 3
    interval: 1000

#===============================================================================

logging.level.org.solar.system.rental.service.feign: DEBUG
