server:
  port: ${MDM_SOURCE_PORT:8071}
  error.include-message: always
    
#===============================================================================

spring:
  application:
    name : ${application.name-key}-rec-service
  output.ansi.enabled: ALWAYS
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${MDM_PG_DB_SERVICE:localhost:5453}/${MDM_PG_DB_NAME:solar-mdm-recette}
    username: ${MDM_PG_DB_USER:r_mdm_user}
    password: ${MDM_PG_DB_PASSWORD:r_mdm_user} # local password : javax123
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 20
      poolName: HIKARI-MDM-REC
      minimumIdle: 2
      leak-detection-threshold: 60000
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect 
    hibernate:
      ddl-auto: update
      jdbc.lob.non_contextual_creation: true
    properties:
      hibernate.format_sql: true # only in dev
      hibernate.id.new_generator_mappings: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.hbm2ddl.auto: none
  flyway:
    enabled: true # change value for taking new files sql
    locations: ${FLYWAY_LOCATIONS:filesystem:C:/mfichtali/projects/solar-depot/ms-mdm-parent/script/recette-pg} # separated by comma
    lockRetryCount: 10