#===============================================================================

server:
  port: ${MDM_SOURCE_PORT:8071}
  error.include-message: always

#===============================================================================
#=================> Logging config

# logging:
#   level:
#     org.springframework.web: INFO
#     org.springframework.web.servlet.DispatcherServlet: INFO
#     org.springframework.web.client.RestTemplate: INFO
#     org.hibernate: INFO
#     org.hibernate.type: INFO
#     org.hibernate.type.descriptor.sql.BasicBinder: TRACE

#===============================================================================
#================ > Spring config

spring:
  # application:
  #   name : ${application.name-key}-dev-service
  # output.ansi.enabled: ALWAYS
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${MDM_PG_DB_SERVICE:localhost:5452}/${MDM_PG_DB_NAME:solar-mdm-dev}
    username: ${MDM_PG_DB_USER:d_mdm_user}
    password: ${MDM_PG_DB_PASSWORD:d_mdm_user} # local password : javax123
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 20
      poolName: HIKARI-MDM-DEV
      minimumIdle: 2
      leak-detection-threshold: 60000
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect 
    hibernate:
      ddl-auto: update
      jdbc.lob.non_contextual_creation: true
    properties:
      org.hibernate.envers.audit_table_suffix: _MDM_DEV_LOG
      hibernate.format_sql: true # only in dev
      hibernate.id.new_generator_mappings: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.hbm2ddl.auto: none
  flyway:
    enabled: true # change value for taking new files sql
    locations: ${FLYWAY_LOCATIONS:filesystem:D:/mfichtali/depots/ms-mdm-parent/script/dev-pg} # separated by comma
    #locations: ${FLYWAY_LOCATIONS:filesystem:/home/mfichtali/workspace/depôt/ms-mdm-parent/script/dev-pg} # separated by comma
    lockRetryCount: 10