services:


  # Begin audit-service [DEV] section 
  audit-service-dev:
    image: audit-service:$AUDIT_VERSION
    container_name: $AUDIT_CONTAINER_NAME
    profiles:
      - dev
    build:
      context: ../../../ms-audit-parent
      args:
        service_name: $AUDIT_SERVICE_NAME
        workdir_env: $ROOT_CONTEXT_APP
        audit_version: $AUDIT_VERSION
        profile_env: $SPRING_PROFILES_ACTIVE 
    env_file:
      - ../../environment/.env.shared
      - ../../environment/.env.ecosystem
      - ../../environment/$SPRING_PROFILES_ACTIVE.env
    volumes:
      - $APP_LOG_VOLUME:$CONTAINER_LOG_PATH
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=$KAFKA_BOOTSTRAP_SERVICE
    ports:
      - $AUDIT_PORT:$AUDIT_CONTAINER_PORT
    # End audit-service [DEV] section
    

networks:
  default:
      name: netix-red
      external: true