services:


  # Begin mdm-service [DEV] section 
  mdm-service-dev:
    image: mdm-service:$MDM_VERSION
    container_name: $MDM_CONTAINER_NAME
    profiles:
      - dev
    build:
      context: ../../../ms-mdm-parent
      args:
        service_name: $MDM_SERVICE_NAME
        workdir_env: $ROOT_CONTEXT_APP
        mdm_version: $MDM_VERSION
        profile_env: $SPRING_PROFILES_ACTIVE 
    env_file:
      - ../../environment/.env.shared
      - ../../environment/.env.ecosystem
      - ../../environment/$SPRING_PROFILES_ACTIVE.env
    volumes:
      - $APP_LOG_VOLUME:$CONTAINER_LOG_PATH
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=$KAFKA_BOOTSTRAP_SERVICE
    ports:
      - $MDM_PORT:$MDM_CONTAINER_PORT
#    depends_on:
#      db-mdm-dev:
#        condition: service_healthy
  # End mdm-service [DEV] section


networks:
  default:
      name: netix-red
      external: true