services:


  # Begin mdm-service [DEV] section
  rental-service-dev:
    image: rental-service:$RENTAL_VERSION
    container_name: $RENTAL_CONTAINER_NAME
    profiles:
      - dev
    build:
      context: ../../../ms-rental-parent
      args:
        workdir_env: $ROOT_CONTEXT_APP
        rental_version: $RENTAL_VERSION
        profile_env: $SPRING_PROFILES_ACTIVE
    env_file:
      - ../../environment/.env.shared
      - ../../environment/.env.ecosystem
      - ../../environment/$SPRING_PROFILES_ACTIVE.env
    volumes:
      - $APP_LOG_VOLUME:$CONTAINER_LOG_PATH
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=$KAFKA_BOOTSTRAP_SERVICE
    ports:
      - $RENTAL_PORT:$RENTAL_CONTAINER_PORT


networks:
  default:
      name: netix-red
      external: true