# version: "3.8"
services:


  # Begin Postgres DEV section 
  db-auth-dev:
    image: postgres:$PG_IMAGE_VERSION
    hostname: $AUTH_PG_DB_SERVICE
    container_name: postgres-auth-$SPRING_PROFILES_ACTIVE
    profiles: ["dev"]
    volumes:
      - $LOCAL_VOLUME_POSTGRES\auth\$SPRING_PROFILES_ACTIVE:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$AUTH_PG_DB_NAME
      - POSTGRES_PASSWORD=$AUTH_PG_DB_USER
      - POSTGRES_USER=$AUTH_PG_DB_PASSWORD
    ports:
      - $AUTH_PG_DB_PORT:$POSTGRES_DEFAULT_PORT
  # End Postgres DEV section 


  # Begin Postgres RECETTE section 
  db-auth-rec:
    image: postgres:$PG_IMAGE_VERSION
    hostname: $AUTH_PG_DB_SERVICE
    container_name: postgres-auth-$SPRING_PROFILES_ACTIVE
    profiles: ["rec"]
    volumes:
      - $LOCAL_VOLUME_POSTGRES\auth\$SPRING_PROFILES_ACTIVE:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$AUTH_PG_DB_NAME
      - POSTGRES_PASSWORD=$AUTH_PG_DB_USER
      - POSTGRES_USER=$AUTH_PG_DB_PASSWORD
    ports:
      - $AUTH_PG_DB_PORT:$POSTGRES_DEFAULT_PORT
  # End Postgres RECETTE section 


  # Begin Auth service [DEV] section 
  auth-service-dev:
    image: auth-service:$AUTH_VERSION
    container_name: $AUTH_CONTAINER_NAME
    profiles: ["dev"]
    env_file: 
      - ./environment/$SPRING_PROFILES_ACTIVE.env
    build:
      context: ../../ms-auth-parent
      args:
        workdir_env: $ROOT_CONTEXT_APP
        profile_env: $SPRING_PROFILES_ACTIVE 
        auth_version: $AUTH_VERSION
    volumes:
      - $APP_LOG_VOLUME:$CONTAINER_LOG_PATH
    ports:
      - $AUTH_PORT_EXPOSE:$AUTH_PORT_SOURCE
    depends_on:
      - postgres-auth-$SPRING_PROFILES_ACTIVE
  # End Auth service [DEV] section 

networks:
  default:
      name: netix-red
      external: true


  # Postgres conf 
  # postgres_db_fake:
  #   image: postgres:$PG_IMAGE_VERSION
  #   container_name: postgres_db_fake
  #   volumes:
  #     - $LOCAL_VOLUME_POSTGRES\fake:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=$POSTGRES_DB_FAKE
  #     - POSTGRES_USER=$POSTGRES_USER_FAKE
  #     - POSTGRES_PASSWORD=$POSTGRES_PASSWORD_FAKE
  #   ports:
  #     - $FAKE_POSTGRES_PORT:$POSTGRES_DEFAULT_PORT
