#===============================================================================

server:
  servlet:
    context-path: /${application.name-key}

#===============================================================================
#========================= > Application Common properties

application:
  swagger:
    title: Authentication API
    description: Authentication Information
    termsOfService: http://swagger.io/terms/
    licenseName: Apache 2.0
    licenseUrl: http://springdoc.org
    activeVersion: 1.0 # swagger version manually changed
    # adminPathToMatchs: /api/version/**
    actuatorPathToMatch: /actuator/**
    publicPathToMatchs: /api/** 
    publicPathToExcludes: /api/v1.0/**    # /api/version/**

  # Enable Kafka Produce message
  #kafka.producer.enabled: false

#===============================================================================
#========================= > Spring config

spring:
  kafka:
    enabled: true
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    no-concurrency: 3
    session-timeout-ms: 30000
    heartbeat-interval-ms: 20000
    max-poll-records: 100
    max-poll-interval-ms: 3000


#===============================================================================
#========================= > Feign config

feign:
  retry:
    maxAttempt: 3
    interval: 1000


#===============================================================================
#========================= > Spring Doc config
# The OpenAPI definitions are in JSON format by default. For yaml format, we can obtain the
# definitions at : http://localhost:8080/api-docs.yaml
# default url : http://localhost:8080/v3/api-docs/
# swagger UI url : http://localhost:8080/swagger-ui.html
springdoc:
  #use-management-port: true
  show-actuator: true
#  paths-to-match: /actuator/**, /api/**
#  paths-to-exclude: /api/v1.0/**, /api/v2.0/**    # /api/version/** : api version admin
#  packages-to-scan: org.solar.system.auth.api.rest # package1, package2
  api-docs: 
    enabled: true # Disabling the /api-docs enpoint
    # path: /api-docs  # url like http://localhost:8080/api-docs/
  swagger-ui:
    enabled: false # Disabling the /swagger-api enpoint
    defaultModelsExpandDepth: -1
    operationsSorter: method
    

#===============================================================================
#========================= > JWT config

jwt:
  header: Access-token
  expirationDurationType: HOUR # HOUR | DAY | MIN (test)
  expiration: 8 # in hour 
  refreshExpiration: 24 # in hour 
