#===============================================================================

#daily rolling logs
#logging.pattern.rolling-file-name=myinfo-%d{yyyy-MM-dd}.%i.log
#per hour rolling logs
#logging.pattern.rolling-file-name=myinfo-%d{yyyy-MM-dd-HH}.%i.log
#per minute rolling logs
#logging.pattern.rolling-file-name=myinfo-%d{yyyy-MM-dd-HH-mm}.%i.log
#per secs rolling logs
# logging.pattern.rolling-file-name=myinfo-%d{yyyy-MM-dd-HH-mm-ss}.%i.log
# logging.file.path: ${CONTAINER_LOG_PATH} : use env variable to describe specific path

logging:
  level:
    root: ERROR
    org.springframework.web.servlet.DispatcherServlet: ERROR
    org.springframework.web: ERROR
    org.hibernate: ERROR
    org.hibernate.type: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # only in dev